name: Release

on:
    push:
        branches:
            - tay-fork

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 30
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v3
              with:
                  run_install: true

            - name: Build
              run: pnpm build

            - name: Create Release Pull Request or Publish to NPM
              id: changesets
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
